import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/Auth";
import { StatusProvider } from "./contexts/UserStatus";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    if (!localStorage.theme) {
        if (
            window.matchMedia &&
            window.matchMedia("(prefers-color-scheme: dark)").matches
        ) {
            localStorage.theme = "dark";
        } else if (
            window.matchMedia &&
            window.matchMedia("(prefers-color-scheme: light)").matches
        ) {
            localStorage.theme = "light";
        } else {
            localStorage.theme = "dark";
        }
    }

    if (
        localStorage.theme === "dark" &&
        !document.documentElement.classList.contains("dark")
    ) {
        document.documentElement.classList.add("dark");
        document.documentElement.classList.remove("light");
    }
    if (
        localStorage.theme === "light" &&
        !document.documentElement.classList.contains("light")
    ) {
        document.documentElement.classList.add("light");
        document.documentElement.classList.remove("dark");
    }

    return (
        <html lang="en">
            <AuthProvider>
                <StatusProvider>
                    <body className={inter.className}>{children}</body>
                </StatusProvider>
            </AuthProvider>
        </html>
    );
}
